version: "3.7"
services:
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: cmu-redis01
    ports:
      - "6379:6379"
    networks: 
      backend_network:
        ipv4_address: 192.168.0.10 

networks: 
  backend_network:
    name: backend
    driver: bridge
    ipam: 
      config: 
        - subnet: "192.168.0.0/25"
          gateway: "192.168.0.1"