version: "3.7"
services:
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: cmu-redis01
    ports:
      - "6379:6379"
    networks: 
      backend_network:
        ipv4_address: 192.168.0.10 

  mysql:
    image: mysql:5.7
    container_name: cmu-mysql01
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=cmu
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Seoul
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d
      - ./init/:/docker-entrypoint-initdb.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks: 
      backend_network:
        ipv4_address: 192.168.0.11

networks: 
  backend_network:
    name: backend
    driver: bridge
    ipam: 
      config: 
        - subnet: "192.168.0.0/25"
          gateway: "192.168.0.1"